Crowdin.sln
src/Crowdin.Api/Client.cs
src/Crowdin.Api/IClient.cs
src/Crowdin.Api/Typed/ClientExtensions.cs
tests/Crowdin.Api.Tests/ClientExtensionsTests.cs
tests/Crowdin.Api.Tests/Crowdin.Api.Tests.csproj

* Refactor Client and ClientExtensions to help with testing.
* Add Test project and first unit test

(#8) Add first unit tests for Crowdin.Api

---

src/Crowdin.Api/Typed/ExportStatus.cs
tests/Crowdin.Api.Tests/Typed/ExportStatusTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crowdin/crowdin-dotnet-client/17)

Parse XML for Translation Export Status

---

src/Crowdin.Api/MachineTranslationEngines/LanguageRecognitionProvider.cs
src/Crowdin.Api/MachineTranslationEngines/MachineTranslationEnginesApiExecutor.cs
src/Crowdin.Api/MachineTranslationEngines/MtTranslation.cs
src/Crowdin.Api/MachineTranslationEngines/TranslateViaMtRequest.cs
src/Crowdin.Api/SourceStrings/SourceString.cs

+ Add new method **Translate via MT**
+ Add new fields for **Source Strings**

API Updates

---

README.md
src/Crowdin.Api/Crowdin.Api.nuspec

- Add new method Translate via MT (#40)
- Add new fields for Source Strings (#40)
- Fix coverage, migration to Coverlet (#35)
- Add missing user role : Owner (#41)
- Fix content type for PATCH routes (#42)
- Fix FileStream in-method disposal (#43)

Version 2.4.0

---

README.md
src/Crowdin.Api/Crowdin.Api.nuspec

- API updates: add BuildProjectDirectoryTranslationRequest.PreserveFolderHierarchy (#45)

Version 2.4.1

---

Crowdin.sln.DotSettings.user
README.md
samples/Crowdin.Api.Samples/Program.cs
src/Crowdin.Api/Core/Resilience/RetryConfiguration.cs
src/Crowdin.Api/Core/Resilience/RetryService.cs
src/Crowdin.Api/CrowdinApiClient.cs
tests/Crowdin.Api.Tests/Common/FetchAllDataTests.cs
tests/Crowdin.Api.Tests/Common/RetryServiceTests.cs

+ Retry configuration
+ `WithFetchAll` method for automatic pagination control
+ Ability to pass externally configured `HttpClient` to API client

Advanced configuration

---

README.md
src/Crowdin.Api/Crowdin.Api.nuspec

* field name `targetLanguagesId` should be `targetLanguageIds` ([https://github.com/crowdin/crowdin-api-client-dotnet/pull/59](https://github.com/crowdin/crowdin-api-client-dotnet/pull/59))

Version 2.5.2

---

README.md
src/Crowdin.Api/Crowdin.Api.nuspec

- API Updates: Users: add InviteUser, DeleteUser, EditUser methods support (#63)
- Fix: errors deserialization & message forming (#62)

Version 2.6.0

---

README.md
src/Crowdin.Api/Crowdin.Api.nuspec

Version 2.7.0

---

tests/Crowdin.Api.Tests/Reports/GroupReportsApiTests.cs
tests/Crowdin.Api.Tests/Reports/OrganizationReportsApiTests.cs
tests/Crowdin.Api.Tests/Reports/ReportSettingsTemplatesApiTests.cs
tests/Crowdin.Api.Tests/Reports/ReportsApiTests.cs

Increased tests coverage for the ReportsApiExecutor.cs class

---

src/Crowdin.Api/Webhooks/EventType.cs
tests/Crowdin.Api.Tests/Webhooks/WebhookEventTypeTests.cs

fix: Add missing webhook events

---

src/Crowdin.Api/SourceFiles/SourceFilesApiExecutor.cs
tests/Crowdin.Api.Tests/Core/Resources/SourceFiles.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/SourceFiles.resx
tests/Crowdin.Api.Tests/SourceFiles/FilesTests.cs

API Updates: Source Files: add DownloadFilePreview method support

---

src/Crowdin.Api/ProjectsGroups/EnterpriseProjectForm.cs
src/Crowdin.Api/ProjectsGroups/FileBasedProjectForm.cs
src/Crowdin.Api/ProjectsGroups/ProjectSettingPatch.cs
src/Crowdin.Api/ProjectsGroups/ProjectSettings.cs
src/Crowdin.Api/ProjectsGroups/StringsBasedProjectForm.cs

API Updates: Projects: add `qaChecksIgnorableCategories` support

---

src/Crowdin.Api/ProjectsGroups/QaCheckCategories.cs

API Updates: QaCheckCategories: add `ftl` and `android` support

---

src/Crowdin.Api/TranslationMemory/TranslationMemory.cs
tests/Crowdin.Api.Tests/Core/Resources/TranslationMemory.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/TranslationMemory.resx
tests/Crowdin.Api.Tests/TranslationMemory/TranslationMemoryApiTests.cs

* Remove "defaultProjectId"
* Add "defaultProjectIds" instead
Closes #111

API Updates: TM: replace deprecated property "defaultProjectId"

---

src/Crowdin.Api/Core/Converters/FileImportOptionsConverter.cs
src/Crowdin.Api/SourceFiles/FileImportOptions.cs
tests/Crowdin.Api.Tests/Core/Resources/SourceFiles.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/SourceFiles.resx
tests/Crowdin.Api.Tests/SourceFiles/AddFileTests.cs

* Html File Import Options
* Html with Front Matter File Import Options
Closes #141

feat(api): source files: add new import options

---

src/Crowdin.Api/Glossaries/Glossary.cs
tests/Crowdin.Api.Tests/Core/Resources/Glossaries.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/Glossaries.resx
tests/Crowdin.Api.Tests/Glossaries/GlossariesApiTests.cs

feat(api): glossaries: add property `defaultProjectIds` support

---

samples/Crowdin.Api.Samples.Actions/Actions/1_CreateFile.cs
samples/Crowdin.Api.Samples.Actions/Actions/2_UpdateFile.cs
samples/Crowdin.Api.Samples.Actions/Actions/3_CreateTm.cs
samples/Crowdin.Api.Samples.Actions/Actions/4_CreateGlossary.cs
samples/Crowdin.Api.Samples.Actions/Actions/5_PreTranslateProject.cs
samples/Crowdin.Api.Samples.Actions/Actions/7_GenerateReport.cs
src/Crowdin.Api/ColumnType.cs
src/Crowdin.Api/Glossaries/GlossaryExportStatus.cs
src/Crowdin.Api/Glossaries/GlossaryImportStatus.cs
src/Crowdin.Api/OperationStatus.cs
src/Crowdin.Api/Reports/GroupReportStatus.cs
src/Crowdin.Api/Reports/ReportStatus.cs
src/Crowdin.Api/TranslationMemory/TmExportStatus.cs
src/Crowdin.Api/TranslationMemory/TmImportStatus.cs
tests/Crowdin.Api.Tests/TranslationMemory/TranslationMemoryApiTests.cs

+ Added enum `OperationStatus` + replaced type of string `Status` properties with it
+ Added static class ColumnType with common column types

feat(api): add enum OperationStatus + class ColumnType

---

src/Crowdin.Api/ProjectsGroups/EnterpriseProjectPatch.cs
src/Crowdin.Api/ProjectsGroups/ProjectSettingPatch.cs
src/Crowdin.Api/ProjectsGroups/ProjectSettings.cs
src/Crowdin.Api/ProjectsGroups/TmPenalties.cs
src/Crowdin.Api/ProjectsGroups/TmPriority.cs
src/Crowdin.Api/ProjectsGroups/TmTimeElapsed.cs
tests/Crowdin.Api.Tests/Core/Resources/Projects.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/Projects.resx
tests/Crowdin.Api.Tests/ProjectsGroups/EditProjectTests.cs
tests/Crowdin.Api.Tests/ProjectsGroups/ProjectsApiTests.cs

feat(api): add TmPenalties property support + more patch paths

---

src/Crowdin.Api/Core/Converters/FileExportOptionsConverter.cs
src/Crowdin.Api/SourceFiles/FileExportOptions.cs
src/Crowdin.Api/SourceFiles/FilePatch.cs
tests/Crowdin.Api.Tests/Core/Resources/SourceFiles.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/SourceFiles.resx
tests/Crowdin.Api.Tests/SourceFiles/AddFileTests.cs
tests/Crowdin.Api.Tests/SourceFiles/FilesTests.cs

feat: Add Javascript File Export Options

---

src/Crowdin.Api/Translations/ApplyPreTranslationRequest.cs
src/Crowdin.Api/Translations/PreTranslateAttributes.cs
tests/Crowdin.Api.Tests/Core/Resources/Translations.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/Translations.resx
tests/Crowdin.Api.Tests/Translations/TranslationsApiTests.cs

feat(api): Labels Support For Pre-Translation API

---

src/Crowdin.Api/StringTranslations/StringTranslationsApiExecutor.cs
src/Crowdin.Api/StringTranslations/TranslationApprovalsListParams.cs
src/Crowdin.Api/StringTranslations/TranslationVotesListParams.cs
tests/Crowdin.Api.Tests/Core/Resources/StringTranslations.Designer.cs
tests/Crowdin.Api.Tests/Core/Resources/StringTranslations.resx
tests/Crowdin.Api.Tests/StringTranslations/StringTranslationsApiTests.cs

feat: Add labelIds and excludeLabelIds params to StringTranslationsAPIs

---

src/Crowdin.Api/Translations/ApplyPreTranslationRequest.cs
src/Crowdin.Api/Translations/PreTranslationMethod.cs
tests/Crowdin.Api.Tests/Translations/TranslationsApiTests.cs

feat(translations): add support for AI Pre-Translation

---

src/Crowdin.Api/ProjectsGroups/EnterpriseProjectForm.cs
src/Crowdin.Api/ProjectsGroups/FileBasedProjectForm.cs
src/Crowdin.Api/ProjectsGroups/ProjectSettingPatch.cs
src/Crowdin.Api/ProjectsGroups/StringsBasedProjectForm.cs

feat(projects): add "defaultTmId" and "defaultGlossaryId" support

---

src/Crowdin.Api/StringTranslations/IStringTranslationsApiExecutor.cs
src/Crowdin.Api/StringTranslations/StringTranslationsApiExecutor.cs
tests/Crowdin.Api.UnitTesting/Tests/StringTranslations/ApprovalsApiTests.cs
tests/Crowdin.Api.UnitTesting/Tests/StringTranslations/StringTranslationsApiTests.cs

feat(string-translations): add endpoint "Remove String Approvals"

---

src/Crowdin.Api/SourceStrings/ISourceStringsApiExecutor.cs
src/Crowdin.Api/SourceStrings/SourceStringsApiExecutor.cs
src/Crowdin.Api/SourceStrings/StringsListParams.cs

feat(source-strings): ListStrings: add taskId param support

---

src/Crowdin.Api/SourceStrings/SourceString.cs

feat(source-strings): add "webUrl" property support

---

src/Crowdin.Api/Glossaries/GlossariesApiExecutor.cs
src/Crowdin.Api/Glossaries/IGlossariesApiExecutor.cs
src/Crowdin.Api/Glossaries/TermsListParams.cs

feat(terms): add croql param support

---

src/Crowdin.Api/Bundles/AddBundleRequest.cs
src/Crowdin.Api/Bundles/Bundle.cs
src/Crowdin.Api/Bundles/BundlePatch.cs

feat(bundles): add missing properties

---

src/Crowdin.Api/Translations/UploadTranslationsRequest.cs
tests/Crowdin.Api.UnitTesting/Tests/Translations/TranslationsApiTests.cs

feat(translations): add property "AddToTm"

---

src/Crowdin.Api/Distributions/Distribution.cs

feat(distributions): add support for "manifestUrl"

---

src/Crowdin.Api/CrowdinApiClient.cs

feat(url): add trailing slash support

---

src/Crowdin.Api/CrowdinApiClient.cs

fix(client): missing IBranchesApiExecutor

---

src/Crowdin.Api/SourceFiles/ProjectFileType.cs

feat(source-files): add ProjectFileType.Xlsx
